##### Packages Used #####

#install.packages("RSelenium")
library(RSelenium)
#install.packages("rvest")
library(rvest)
#install.packages("tibble")
library(tibble)
# install.packages("tidyverse")
library(tidyverse)
#install.packages("data.table")
library(data.table)
#install.packages("lubridate")
library(lubridate)
#install.packages("ggplot2")
library(ggplot2)
#install.packages("hrbrthemes")
library(hrbrthemes)
#install.packages("viridis")
library(viridis)
# install.packages("ggridges")
library(ggridges)